- hosts: all
  become: true
  remote_user: vagrant
  become_user: root
  tasks:
    - name: Install httpd
      yum:
        name: httpd

    - name: Make sure Apache is running
      service:
        name: httpd
        state: started

    - name: Verify Firewall
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Restart firewall
      service:
        name: firewalld
        state: restarted