- hosts: all
  become: true
  remote_user: vagrant
  become_user: root
  tasks:
    - name: Setting SELinux
      yum:
        name: libselinux-python
        state: installed

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Setting Timezone
      timezone:
        name: Asia/Tokyo

    # yum install
    - name: EPEL Repository
      yum:
        name: epel-release
        state: latest

    - name: Remi repository
      command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

    - name: Install Git
      yum:
        name: git
        state: latest

    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Install Redis
      yum:
        name: redis
        state: latest

    - name: Install PHP 7.4
      yum: 
        name: [
          php,
          php-devel,
          php-common,
          php-fpm,
          php-opcache,
          php-pecl-redis,
          php-mbstring,
          php-mcrypt,
          php-mysqlnd,
          php-pdo,
          php-gd,
          php-xml,
          php-zip
        ]
        enablerepo: remi,remi-php74
        state: latest
    # mysql
    - name: Download MySQL Community
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: present
    - name: Delete mariadb
      yum:
        name: mariadb-libs
        state: removed
    - name: Install MySQL 8
      yum:
        name: ['mysql-community-devel*', 'mysql-community-server*', 'MySQL-python']
        state: present
    - name: enable mysql
      systemd:
        name: mysqld
        state: started
        enabled: yes
    - name: get root password
      shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
      register: root_password
    - name: debug gegister
      debug: var=root_password
    - name: Copy db access file
      copy:
        src: ../files/tmp/tmp_dbaccess.cnf
        dest: /tmp/tmp_dbaccess.cnf
        mode: 0644
        owner: vagrant
        group: vagrant
    - name: Edit db access file
      lineinfile:
        dest: /tmp/tmp_dbaccess.cnf
        regexp: '\password =$'
        line: "password = '{{ root_password.stdout }}'"
    - name: Copy my.conf
      copy:
        src: ../files/etc/my.cnf
        dest: /etc/my.cnf
        mode: 0644
    - name: enable mysql
      systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: echo new password
      shell: 'echo Ft[Jkz.Jcvn^9M8b'
      register: new_password
    - name: debug gegister
      debug: var=new_password
    - name: update expired root user password
      command: mysql --defaults-extra-file=/tmp/tmp_dbaccess.cnf --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ new_password.stdout }}';"
    - name: Create a new database with name 'sampledb'
      mysql_db:
        login_user: root
        login_password: "{{ new_password.stdout }}"
        name: sampledb
        state: present
    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Start Redis
      service:
        name: redis
        state: started
        enabled: true

    - name: firewalld Disable
      systemd:
        name: firewalld
        state: stopped
        enabled: false

    # Composer
    - name: Install Composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin && mv /bin/composer.phar /bin/composer
      args:
        creates: /bin/composer

    # php.ini 編集
    - name: Setting php.ini -timezone
      replace:
        path: /etc/php.ini
        regexp: "^;date.timezone ="
        replace: date.timezone = Asia/Tokyo

    # 設定ファイルのコピー
    - name: Setting file httpd backup
      command: cp -p /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.org
    - name: Setting file httpd copy
      command: cp -p /vagrant/files/etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf
    - name: Setting file vhttpd copy
      command: cp -p /vagrant/files/etc/httpd/conf.d/sampleproject.conf /etc/httpd/conf.d/sampleproject.conf

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
